version: '3.8'

networks:
    net_postgres:
        name: NetPostgres
        driver: bridge
        ipam:
            config:
                - subnet: 172.60.60.0/16
volumes:
    dbdata:
        driver: local

services:
    postgres:
        image: postgres
        restart: always
        container_name: postgres
        environment:
            POSTGRES_PASSWORD: example
        volumes:
            - dbdata:/var/lib/oracle
        networks:
            net_postgres:
                ipv4_address: 172.60.62.1